My_Blog_Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#from app_blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_login.urls')),
    path('blog/', include('app_blog.urls')),
    path('', views.Index, name='index')
]

My_Blog_Project/app_blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app_blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list')
]

My_Blog_Project/app_login/urls.py
from django.urls import path,re_path 
from . import views
app_name = 'app_login'

urlpatterns = [
    path('signup/',views.signup, name = 'signup'),
    path('login/',views.login_page, name = 'login'),
    path('logout/', views.logout_user, name = 'logout')
]

My_Blog_Project/app_blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name='Put a title')
    slug = models.SlugField(max_length=265,unique=True)
    blog_content = models.TextField( verbose_name='wWhat is in your mind')
    blog_image = models.ImageField( upload_to='blog_images', verbose_name='Images')
    publish_date = models.DateTimeField( auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, related_name='blog_comment', on_delete=models.CASCADE)
    user = models.ForeignKey(Blog, related_name='user_comment', on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

class Likes(models.Model):
    blog = models.ForeignKey(Blog, related_name='liked_blog', on_delete=models.CASCADE)
    user = models.ForeignKey(Blog, related_name='liker_user', on_delete=models.CASCADE)
    

My_Blog_Project/app_login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="profile_pics")

My_Blog_Project/My_Blog_Project/views.py
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
def Index(request):
    return HttpResponseRedirect(reverse('app_blog:blog_list'))

My_Blog_Project/app_blog/views.py
from django.shortcuts import render 

# Create your views here.

def blog_list(request):
    return render(request, 'app_blog/blog_list.html',context={})

My_Blog_Project/app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def signup(request):
    form = UserCreationForm()
    registered= False
    if request.method=='POST':
        form = UserCreationForm(data = request.POST)
        if form.is_valid():
            form.save()
            registered=True
    dict={'form':form, 'registered':registered}
    return render(request, 'app_login/signup.html',context=dict)

def login_page(request):
    form = AuthenticationForm()
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username= form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
    dict={'form':form}
    return render(request, 'app_login/login.html', context=dict)
@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

My_Blog_Project/templates/app_blog/blog_list.html
{% extends 'base.html' %}
{% block title_block %} Home {% endblock %}

{% block bodyblock %}

<h1> I am Blog Homepage </h1>



{% endblock %}

My_Blog_Project/templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %} Login {% endblock %}
    
{% block bodyblock %}
<form method="POST">
<h2>Login</h2>
 {{form|crispy}}
 {% csrf_token %}
 <button type='submit' class='btn btn-primary btn-sm'>Log in </button>
 </form>
{% endblock %}
    

My_Blog_Project/templates/app_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Sign Up here {% endblock %}

{% block bodyblock %}
{% if registered %}
<div class='alert alert-success'>
    Account is created already <a href={% url 'app_login:login' %}>Login Here </a>
</div>

{% else %}

<h2> Create your Account </h2>
<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
     <button type="submit" class="btn btn-sm btn-success" name="button"> Submit </button>
</form>
<br>
<p> Already Have an account <a href={% url 'app_login:login' %}> Login Here </a> </p>

{% endif %}

{% endblock %}

My_Blog_Project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>{% block title_block %}Blogs{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
       <ul class="navbar-nav">
         <li class="nav-item active">
           <a class="nav-link" href="{% url 'index' %}">Home</a>
         </li>
         
         {% if user.is_authenticated %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'app_login:logout' %}">Logout</a>
         </li>
         {% else %}
         
         <li class="nav-item">
           <a class="nav-link" href="{% url 'app_login:signup' %}">Sign Up</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="{% url 'app_login:login' %}">Login</a>
        </li>


         {% endif %}
          
         
        
       </ul>
     </nav>
     <div class="container" style= "padding-up:20px">
      {% block bodyblock %}

       {% endblock %}
     </div>
     
  </body>
</html